<a href="https://colab.research.google.com/github/vasantbala/vb_ai_course/blob/main/McCullohPitt_RosenBlat_Neurons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from random import choice
from numpy import array, dot, random

import numpy as np;


In [3]:
# MCNeuron for And

w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
      (array([0,0]), 0),
      (array([0,1]), 0),
      (array([1,0]), 0),
      (array([1,1]), 1)
]

step_function = lambda x: 0 if x < 2 else 1

for x, _ in training_data:
  result = dot(x,w)
  print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 0
[1 0]: 1.0 -> 0
[1 1]: 2.0 -> 1


In [4]:
# MCNeuron for Or

w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
      (array([0,0]), 0),
      (array([0,1]), 1),
      (array([1,0]), 1),
      (array([1,1]), 1)
]

step_function = lambda x: 0 if x < 1 else 1

for x, _ in training_data:
  result = dot(x,w)
  print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 1


In [6]:
# MCNeuron for NAND

w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 1),
    (array([0,1]), 1),
    (array([1,0]), 1),
    (array([1,1]), 0),
]

step_function = lambda x: 0 if x > 1 else 1

for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))

[0 0]: 0.0 -> 1
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 0


In [7]:
# Rosenblat's Perceptron included a way to adjust the weights and find the appropriate combinations 
# to overcome the need to modify thresholds for each gate separately, it used a bias term using which the thresholds in the 
# neuron can be modified to implement multiple Boolean functions in one code

In [8]:
step_function = lambda x: 0 if x < 100 else 1    # Step function with threshold of 0.5. Anything below is 0 


# AND gate
training_data = [
    (array([0,0 ,1]), 0),
    (array([0,1, 1]), 0),
    (array([1,0, 1]), 0),
    (array([1,1, 1]), 1),
]

w = random.rand(3)
print(w)

errors = []
eta = 0.1
n = 100000

for i in range(n):
    x, expected = choice(training_data)


    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                       # that is the beauty of bias. The 'AND' pattern is learnt from data
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))

[0.57935803 0.24777385 0.98726314]
[0 0 1]: 33.787263136671136 -> 0
[0 1 1]: 66.83503698216288 -> 0
[1 0 1]: 67.16662116662741 -> 0
[1 1 1]: 100.21439501211916 -> 1


In [9]:
step_function = lambda x: 0 if x < 100 else 1    # Step function with threshold of 0.5. Anything below is 0 


# OR gate
training_data = [
    (array([0,0 ,1]), 0),
    (array([0,1, 1]), 1),
    (array([1,0, 1]), 1),
    (array([1,1, 1]), 1),
]

w = random.rand(3)
print(w)

errors = []
eta = 0.1
n = 100000

for i in range(n):
    x, expected = choice(training_data)


    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                       # that is the beauty of bias. The 'AND' pattern is learnt from data
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))

[0.74425456 0.41239391 0.64497321]
[0 0 1]: 62.74497321196064 -> 0
[0 1 1]: 100.15736712644593 -> 1
[1 0 1]: 102.189227772386 -> 1
[1 1 1]: 139.60162168687128 -> 1
